name: Daily Run main.py

on:
  push:
  schedule:
    - cron: "25 14 * * *"  # Runs at 10:25 AM Eastern Time daily (14:25 UTC)
    - cron: "0 4 * * *"    # Runs at 12:00 AM Eastern Time daily (04:00 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run script
        run: python main.py
